// Predefined transaction descriptions that can be used on the client side
export const DEFAULT_DESCRIPTIONS = [
  "Home Insurance",
  "Utilities",
  "Groceries",
  "Internet",
  "Mobile phone",
  "Car (gas)",
  "Clothing",
  "Pharmacy",
  "Coffee",
  "Mortgage",
  "Bonus",
  "Gym",
  "Liquor Store",
  "Restaurant",
  "Electric Bill",
  "Gas Bill",
  "Water Bill",
  "Rent",
  "Car Insurance",
  "Health Insurance",
  "Dental Care",
  "Eye Care",
  "Subscription",
  "Entertainment",
  "Shopping",
  "Transportation",
  "Fuel",
  "Parking",
  "Taxi/Uber",
  "Public Transport",
  "Flight",
  "Hotel",
  "Vacation",
  "Gift",
  "Donation",
  "Tax",
  "Bank Fee",
  "Investment",
  "Savings",
  "Salary",
  "Freelance",
  "Business Income",
  "Interest",
  "Dividend",
  "Refund",
  "Cashback",
  "Other Income"
]
