// Predefined categories based on the current app structure
export const DEFAULT_CATEGORIES = [
  { name: "Food", color: "#ef4444" },
  { name: "Health/medical", color: "#10b981" },
  { name: "Home", color: "#3b82f6" },
  { name: "Home purchase", color: "#8b5cf6" },
  { name: "Car", color: "#f59e0b" },
  { name: "Travel", color: "#06b6d4" },
  { name: "Payroll", color: "#84cc16" },
  { name: "Other", color: "#6b7280" },
  { name: "Recreation", color: "#ec4899" },
  { name: "Government", color: "#ef4444" },
  { name: "Gifts", color: "#f97316" },
  { name: "House Supply", color: "#3b82f6" },
  { name: "Basement", color: "#8b5cf6" },
  { name: "Services", color: "#06b6d4" },
]

// Predefined transaction descriptions based on the current app structure
export const DEFAULT_DESCRIPTIONS = [
  "Home Insurance",
  "Utilities",
  "Groceries",
  "Internet",
  "Mobile phone",
  "Car (gas)",
  "Clothing",
  "Pharmacy",
  "Coffee",
  "Mortgage",
  "Bonus",
  "Gym",
  "Liquor Store",
  "Restaurant",
  "Electric Bill",
  "Gas Bill",
  "Water Bill",
  "Rent",
  "Car Insurance",
  "Health Insurance",
  "Dental Care",
  "Eye Care",
  "Subscription",
  "Entertainment",
  "Shopping",
  "Transportation",
  "Fuel",
  "Parking",
  "Taxi/Uber",
  "Public Transport",
  "Flight",
  "Hotel",
  "Vacation",
  "Gift",
  "Donation",
  "Tax",
  "Bank Fee",
  "Investment",
  "Savings",
  "Salary",
  "Freelance",
  "Business Income",
  "Interest",
  "Dividend",
  "Refund",
  "Cashback",
  "Other Income"
]
